# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'KFCollectionViewAutoSizeLayout-demo' do
pod 'KFCollectionViewLayout', :path => '../../KFCollectionViewLayout.podspec'
end

target 'KFCollectionViewAutoSizeLayout-demoTests' do

end

